### ISSUE TITLE
Won't show up in WoW addons

### ISSUE THREAD

**Issue by jonasd1** [Terrub/Samuel#1]
Hey, I wanted to test out your addon at it is exactly what I was looking for. 

Unfortunately it won't show up under my addons neither can I get it to work via the commands in game. I installed it exactly the way you instructed it. I'm using the kronos client 1.12.1. 

Hope you can help :) 

Best regards

**Comment by Terrub** [comment]
Hey jonasd1,

If the addon doesn't even show up in the addons list inside the game, it means it's not in the right location or doesn't have all the required files.

Can you verify that you have put the files in the right location? You can google "How to find my wow addons folder" for instructions.

If you have the right folder then you should be able to find your interface folder in there. It should look like this:
```
Interface
┗ AddOns
  ┗ Samuel
    ┣ Samuel.lua
    ┗ Samuel.toc
```

Hope that helps clear up any problems.

If not, please let me know.

**Comment by Terrub** [comment]
Issue doesn't seem to be active any more.
Closing
