### ISSUE TITLE
Offhand strikes Reset Swing Timer

### ISSUE THREAD

**Issue by Snektopus** [Terrub/Samuel#10]
Client: Turtle_Wow 1.16.3

Offhand Hits resets 'swing timer' for MH

**Comment by Terrub** [comment]
I hope to have fixed most of the bigger issues with MH bar being reset by OH, there is also an OH bar now, but that's still wonky.
The API does not tell me whether MH or OH hit so there's some new heuristics involved and it's not perfect. Let me know if running MH bar only works well now. OH bar is a WIP i fear.
