### ISSUE TITLE
Error on first load

### ISSUE THREAD

**Issue by Moonchill** [Terrub/Samuel#5]
Got this error when trying to activate the add-on for the first time:

Date: 2019-09-06 18:03:20
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Samuel\Samuel.lua line 398:
   Attempt to register unknown event "CHAT_MSG_COMBAT_SELF_HITS"
Debug:
   [C]: RegisterEvent()
   Samuel\Samuel.lua:398:
      Samuel\Samuel.lua:385
   Samuel\Samuel.lua:868:
      Samuel\Samuel.lua:866
   Samuel\Samuel.lua:914:
      Samuel\Samuel.lua:889
   Samuel\Samuel.lua:947:
      Samuel\Samuel.lua:939
   Samuel\Samuel.lua:983: execute()
   Samuel\Samuel.lua:1013: ?()
   ..\FrameXML\ChatFrame.lua:4606: ChatEdit_ParseText()
   ..\FrameXML\ChatFrame.lua:4267: ChatEdit_SendText()
   ..\FrameXML\ChatFrame.lua:4303: ChatEdit_OnEnterPressed()
   [string "*:OnEnterPressed"]:1:
      [string "*:OnEnterPressed"]:1
Locals:
(*temporary) = Samuel {
 0 = <userdata>
}
(*temporary) = "CHAT_MSG_COMBAT_SELF_HITS"

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.3.2
  AllyRoute, v1.0
  AtlasLootClassic, vv1.1.7-beta1
  AucAdvanced, v8.2.6385 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6368 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.8
  Bartender4, v4.8.5
  BeanCounter, v8.2.6381 (SwimmingSeadragon)
  Enchantrix, v8.2.6392 (SwimmingSeadragon)
  FieldGuide, vv1.4-release
  GatherMate2, v1.45
  Informant, v8.2.6374 (SwimmingSeadragon)
  LeatrixMaps, v1.13.27
  LeatrixPlus, v1.13.26
  LunaUnitFrames, v1.0
  MikScrollingBattleText, v5.7.149
  OmniCC, v8.1.1
  Quartz, v3.5.1
  Questie, v4.0.12 BETA
  RealMobHealth, v2.3
  Samuel, v0.0.1
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  VendorPrice, v1.1.4
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=445)

**Comment by Terrub** [comment]
You seem to be using my addon on WoW Classic. They chose to use a modern client to run the old game there, which means the new API should be used. My addon still comes from the time of the original vanilla client and is not compatible (yet?) with WoW Classic client. Sorry =/
